version: "3.8"
services:
  postgres-read-1:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
    volumes:
      - db-read-1-volume:/var/lib/postgresql/data
    networks:
      - db-network
  postgres-read-2:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
    volumes:
      - db-read-2-volume:/var/lib/postgresql/data
    networks:
      - db-network
  postgres-write:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
    volumes:
      - db-write-volume:/var/lib/postgresql/data
    networks:
      - db-network

volumes:
  db-read-1-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
  db-read-2-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
  db-write-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
networks:
  db-network:
    driver: bridge
